// <auto-generated />
namespace AdoWinFormsLAB15_CodeFirst1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class newNameMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newNameMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202004031653348_newNameMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
